CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(10) NOT NULL,
  username TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bets (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT,
  evidence TEXT NOT NULL,
  wager INTEGER NOT NULL CHECK (wager > 0),
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
